name: "🐛 Bug Report"
description: "Report a bug. Please include information to reproduce."
title: "[Bug Report]: "
labels: ["bug"]
body:
- type: input
  id: version
  attributes:
    label: "Version:"
    description: "What versions of sjgl are effected?"
    placeholder: "e.g. 1.1.2 only, 1.3.*, 1.1.4<="
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: "Reproduction Steps:"
    description: "What are the required steps to reproduce the bug?"
    placeholder: |
      1. ...
      2. ...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: "Expected behavior:"
    description: "What is the expected behavior?"
    placeholder: "e.g. function foo should return bar ..."
  validations:
    required: true
- type: textarea
  id: observed
  attributes: 
    label: "Observed behavior:"
    description: "What is the observered behavior produced by the bug?"
    placeholder: "e.g. function foo returned ..."
  validations:
    required: true
- type: markdown
  id: notes
  attributes:
    value: "Additional notes: "
  validations:
    required: false